= CCUF Team Tools Working Group
:showtitle:
:imagesdir: images
:revnumber: 0.7
:revdate: 2021-03-23

include::menu-include.adoc[]

== Introduction
The CCUF established the Team Tools Working Group to work on a set of tools for iTCs. The overall goal is to produce a set of guidance documents on how to use the tools for an iTC and templates for the documents the iTC will need (both to product, such as a cPP and for the processes of managing the iTC itself). The output from this group is intended to be freely available to all iTCs, and will hopefully be maintained over the long term.

The work is being done in GitHub at https://github.com/itc-wgtools/. There aer multiple repositories for different aspects of the tools, from the cPP templates, to iTC templates to guidance docs and tools created by the WG.

To join the Team Tools WG, please send a message to: ccuf-team-tools-wg@googlegroups.com

To see the calendar for calls/meetings, go to: http://localendar.com/public/itctools

== Tools and Guidance
Any set of tools on its own isn't very useful, so in conjunction with the tools in GitHub is a set of documentation provided on this site to help explain how to use the tools and some of the general back end work that needs to be done to support the iTC.

The guidance is broken into three areas:

* link:/admin-guide/index.html[Administrator Guidance]
* link:/user-guide/index.html[User Guidance]
* link:/examples/examples.html[Examples for the cPPs and SD]

Documents that are available for public review can be seen at the link:/drafts/drafts.html[Drafts] page. This will include information about submitting comments to the WG.

== External Training References
While a lot effort has gone into creating documentation about how to best use GitHub, there are other materials available that may be better (though less focused on the CC usage). Two that have been found are:

* https://www.youtube.com/playlist?list=PLRqwX-V7Uu6ZF9C0YMKuns9sLDzK6zoiV[Git and GitHub for Poets - YouTube series] (free)
* https://www.udemy.com/course/git-and-github-for-writers/[Git and GitHub for Writers by Udemy] (this has a cost associated with it)

These are provided as additional resources, and are not intended as replacement training.

== Current Status
The WG has published a set of templates and documentation and has been updating it based on feedback from iTCs as it has been used. As a volunteer effort, our focus is first on specific requests that are brought up by people using the provided tools and information before moving on to new content.

== Eating Your Own Dog Food
This WG has been attempting to use what we are providing for the wider community. This has helped (and probably hurt initially as we all learned), but hopefully the efforts of the WG will benefit the wider community as we go forward.